### ISSUE TITLE
Same data set used in both fine tune and test as per arguments,  data/finetuning_datasets/classification/bbbp/test.csv is missing from folder

### ISSUE THREAD

**Issue by Parikshit-DartCoder** [HUBioDataLab/SELFormer#4]

**Comment by ervau** [comment]
Hi @Parikshit-DartCoder, thank you for bringing this issue to our attention. I understand the confusion regarding the missing file "data/finetuning_datasets/classification/bbbp/test.csv". Allow me to clarify the process we follow for fine-tuning and testing.

In our workflow, we employ independent data splits for fine-tuning and testing. Instead of saving the train/validation/test sets as individual files, we handle the splitting directly within the scripts. If you'd like to see an example of this process, you can refer to [this section of the code](https://github.com/HUBioDataLab/SELFormer/blob/8ae5618283eaf3ac8dfdadd772d6b94b964a4cc9/train_classification_model.py#LL100C1-L113C28), which demonstrates how the data is split for fine-tuning and testing on the classification tasks.

Previously, we mentioned the "data/finetuning_datasets/classification/bbbp/test.csv" file as a file containing molecule SMILES for which a user want to generate predictions using the fine-tuned models. We understand that these file and argument names may have caused confusion. To address this, we have updated both the file name and the corresponding argument name. Instead, we have provided [a toy dataset](https://github.com/HUBioDataLab/SELFormer/blob/8ae5618283eaf3ac8dfdadd772d6b94b964a4cc9/data/finetuning_datasets/classification/bbbp/bbbp_mock.csv) containing 10 molecules. You can utilize this dataset by using the updated argument to generate predictions using the fine-tuned models. For more detailed information, please refer to the updated "Producing Molecular Property Predictions with Fine-tuned Models" section of the README.

If you have any further questions or need additional assistance, please let me know!

**Comment by ervau** [comment]
Closing this for now due to inactivity. If you require further assistance, please feel free to reopen it.
