### ISSUE TITLE
What is difference in modelO, modelC, modelM

### ISSUE THREAD

**Issue by Chanwhistle** [HUBioDataLab/SELFormer#5]
Hi, I want to do regression task with your model.
You uploaded 3 models in cloud, modelO, modelC, modelM.

What is different in those 3 models?

I fine-tuned modelO, but it doesn't do well with it.
So I will try all of the model, but I want to be clear.

Thanks

**Comment by CyberCatQ** [comment]
Hi, I had the same question and I found that the author already explained it in another issue:
#1 
ModelO should be SELFormer and ModelM should be SELFormer-Lite.

**Comment by Chanwhistle** [comment]
Thanks a lot!

**Comment by ervau** [comment]
Hello,
Sorry for the late response, and thank you for your interest in our models. Have you encountered any ongoing issues with model performance, or have you made improvements since then? If not, could you please share the specific task for which you fine-tuned the models and the results you obtained?
